site_name: Slicer
site_description: Slicer up bare-metal into microVMs
site_author: OpenFaaS Ltd
site_url: https://docs.slicervm.com/

# Repository
repo_name: slicervm/docs.slicervm.com
repo_url: https://github.com/slicervm/docs.slicervm.com
edit_uri: ""

copyright: |
  Copyright &copy; 2025 OpenFaaS Ltd
theme:
  name: material
  # custom_dir: docs/theme
  logo: images/logo.png

  palette:
    - scheme: default
      primary: black
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

  font:
    text: Roboto, Helvetica
    code: Roboto Mono
  features:
    - navigation.tracking
    - navigation.sections
    - navigation.expand

  include_search_page: false
  search_index_only: true

  language: en

  favicon: images/favicon.ico

extra:
  search:
    languages: "en"
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/self-actuated/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/selfactuated

plugins:
  - search

markdown_extensions:
  - attr_list
  - tables
  - md_in_html
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      # emoji_generator: !!python/name:pymdownx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - Overview:
      - Introduction: index.md
      - Contact us: contact.md
  - Getting Started:
      - Installation: getting-started/install.md
      - Walkthrough: getting-started/walkthrough.md
      - Running in the background: getting-started/daemon.md
  - Examples:
      - Run a one-shot task via API: examples/run-a-task.md
      - Kubernetes:
          - HA Kubernetes: examples/ha-k3s.md
          - Large scale Kubernetes: examples/large-scale-k3s.md
          - Multiple machine Kubernetes: examples/multiple-machine-k3s.md
          - K3s with a GPU: examples/k3s-gpu.md
          - OpenFaaS on K3s: examples/openfaas.md
          - Autoscaling Kubernetes: examples/cluster-autoscaler.md
      - AI/LLMs:
          - Ollama with a GPU: examples/gpu-ollama.md
          - Headless OpenCode AI Agent: examples/opencode-ai-agent.md
          - Headless Cursor AI Agent: examples/cursor-cli-agent.md
      - Productivity:
          - Remote Docker builds over SSH: examples/buildkit.md
          - Remote VSCode: examples/remote-vscode.md
          - PiHole Adblocker: examples/pihole-adblock.md
      - Run Jenkins for CI/CD: examples/jenkins.md
      - Run containers with Docker: examples/docker.md
      - OpenFaaS Edge (All-In-One): examples/openfaas-edge.md
  - Tasks:
      - Customise with userdata: tasks/userdata.md
      - Build a custom root filesystem: tasks/custom-image.md
      - Logs & Monitoring: tasks/monitoring.md
      - Share files with NFS: tasks/share-files-with-nfs.md
      - Nested Virtualization: tasks/nested-virtualization.md
  - Storage:
      - Overview: storage/overview.md
      - ZFS: storage/zfs.md
      - Devmapper: storage/devmapper.md
  - Reference:
      - Slicer REST API: reference/api.md
      - Images for microVMs: reference/images.md
      - SSH access to VMs: reference/ssh.md
      - Serial Over SSH (SOS): reference/sos.md
      - VFIO Passthrough: reference/vfio.md
      - Troubleshooting: reference/troubleshooting.md
# extra:
#   analytics:
#     provider: google
#     property: G-PTK21TFJ7V
#     anonymize_ip: true
